### ISSUE TITLE
Marker_1.0.0_aarch64.dmg does not work on apple M3 on macOS 14.3.1 (23D60)

### ISSUE THREAD

**Issue by nikolaydubina** [tk04/Marker#1]
getting

```
“Marker” is damaged and can’t be opened. 
```

**Comment by jacobwood27** [comment]
+1 on M2 Macbook Air

**Comment by fxn** [comment]
`xattr -c /Applications/Marker.app` worked for me (it is in the README).

**Comment by jacobwood27** [comment]
> `xattr -c /Applications/Marker.app` worked for me (it is in the README).

Should have read the readme, this worked for me!
