### ISSUE TITLE
[DEB] libssl.so.1.1: cannot open shared object file

### ISSUE THREAD

**Issue by gander** [tk04/Marker#14]
What|Value
---|---
System| Linux Mint `21.3`
Distro|Ubuntu `22.04`
Version| `1.0.0`
Package| `DEB`

Error:

```
marker: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by tk04** [comment]
fixed in [v1.0.1-dev](https://github.com/tk04/Marker/tree/v1.0.1-dev).
