### ISSUE TITLE
Support `.mdx` files

### ISSUE THREAD

**Issue by deadcoder0904** [tk04/Marker#16]
I sometimes use `.mdx` to write markdown.

It allows for JSX too.

Would love if Marker supports that.

**Comment by edbrannin** [comment]
[Not a maintainer] 

When you use MDX outside a React project or static site generator, where do the components come from?

**Comment by deadcoder0904** [comment]
you either import them just like you import js functions using "../components/CodeBlock.tsx" relative paths or "@/components/CodeBlock.tsx" absolute path. [watch this video to see a demo.](https://www.youtube.com/watch?v=ICcCjGjsWTk)

for me, i personally like writing `.md` but always use `.mdx` files so i guess a simple support would be cool as it could require only adding one more item to array `[".md", ".mdx"]` instead of `[".md"]`.

**Comment by deadcoder0904** [comment]
oopsie, just re-read your question.

i don't use it outside reactjs lol.

my blog is in nextjs so i just write stuff in it using `.md` but the extensions are `.mdx` for some syntax styles.

**Comment by tk04** [comment]
Our editor only supports markdown content. MDX syntax is not supported, so it doesn't make sense to allow you to load `.mdx` files in the app.

**Comment by deadcoder0904** [comment]
@tk04 you only need to change the place where you load `.mdx` file & load it just like `.md`. yes, it'll be half-assed but still it'll work.

i guess you probably have a glob for loading `.md`, you can add `.md|.mdx` :)

**Comment by edbrannin** [comment]
@deadcoder0904 Considering the editor apparently also _clobbers HTML_ (#13) I can't say I'm surprised.

Even if you used Marker to edit a React project's `mdx` files, it would probably drop the React markup anyway.

**Comment by deadcoder0904** [comment]
whoops, will stick with sublime :)
