### ISSUE TITLE
please state which markdown-flavour you use ?

### ISSUE THREAD

**Issue by Asc2011** [tk04/Marker#2]
Hi and great app,

i'd like to use it with Markdeep ? Do you have any plans to allow the user choose his/her prefered markdown-flavour ?

greets, Andreas

**Comment by m-p-3** [comment]
It's based on marked
https://github.com/tk04/Marker/blob/2638283084c81d86722a68b0150f924de761d16b/src/utils/markdown.ts#L3

which according to the [specs](https://marked.js.org/#specifications) is supporting a combination of the original+CommonMark+GitHub features.

**Comment by tk04** [comment]
> i'd like to use it with Markdeep ? Do you have any plans to allow the user choose his/her prefered markdown-flavour ?

This would be a cool idea, but currently, there's no plan to offer different markdown flavors. Willing to consider this for future versions.

**Comment by Asc2011** [comment]
>  Willing to consider this for future versions.

thx - great, i'll keep an eye on the progress.
