### ISSUE TITLE
Sidebar sort options

### ISSUE THREAD

**Issue by infotexture** [tk04/Marker#20]
In projects with large numbers of files, it would be helpful to be able to choose how files in the sidebar are sorted.

Common options include:

- Alphabetically (ascending/descending)
- By modification date (ascending/descending)

**Comment by tk04** [comment]
Added in [v1.1.0](https://github.com/tk04/Marker/releases/tag/master). You can now sort your files by name, creation date, or modification date.

**Comment by infotexture** [comment]
Nice, thanks for implementing this so quickly.
