### ISSUE TITLE
Table of contents panel

### ISSUE THREAD

**Issue by infotexture** [tk04/Marker#21]
In large files, it would be nice to have a way to navigate between heading levels in the file.

Many tools solve this with a right sidebar that displays the hierarchy of Markdown headings, and scrolls to the corresponding position in the file when a heading is clicked.

**Comment by tk04** [comment]
Great suggestion, added in [v1.1.0](https://github.com/tk04/Marker/releases/tag/master). Try it out and let me know your thoughts on it.

**Comment by infotexture** [comment]
That was fast. Well done, thanks. 👏
