### ISSUE TITLE
Ability to Rename file

### ISSUE THREAD

**Issue by bhavaniravi** [tk04/Marker#24]
What the title says, ability to rename the file from the window. Currently there aren't any option even on right click.

**Operating System**

Mac Sonoma 14.4

**Comment by davehope** [comment]
In addition to rename, delete would be a really useful action. I often start with a sort of dumping ground for notes before moving to more structure later and want to remove the temporary file afterwards.

**Comment by tk04** [comment]
Will be adding this in the next release. Delete & rename options will show when your right click on a file.

**Comment by tk04** [comment]
Added in v1.3.0
