### ISSUE TITLE
Empty Title & Subtitle fields not displaying as empty

### ISSUE THREAD

**Issue by wilsocr88** [tk04/Marker#31]
If the title and subtitle fields in a file are empty, switching to that file from another file that does NOT have empty headers results in the headers displaying as though they are present in the file with no headers.

Steps to reproduce:
1. Create a file with text entered in the Title and Subtitle fields
2. Create a new file and leave all fields empty
3. Click the file with text entered in the Title and Subtitle fields
4. Click the new empty file. Notice that the Title and Subtitle fields are not cleared

**Comment by wilsocr88** [comment]
I can't seem to build or debug this but when setting the metadata as an empty object {} to clear it, I suspect it would help if you enumerate out the whole object with title and subtitle as explicitly empty strings.

**Comment by tk04** [comment]
Thanks for the info. Will look into it & hopefully fix it in the next release!

**Comment by tk04** [comment]
Fixed in [v1.4.1](https://github.com/tk04/Marker/releases/tag/master)
