### ISSUE TITLE
Release instructions

### ISSUE THREAD

**Issue by chasingtheflow** [tk04/Marker#5]
In your release instructions you state the following:

> After you download the app and drag it to your Applications folder, you will face difficulties opening it because I'm not enrolled in the Apple Developer Program. To bypass this, you will need to run this in your terminal:
> 
> $ xattr -c /Applications/Marker.app
> After that, you should be able to open the app with no issues.

At least on my machine, you can also just right click the App and choose "Open" from the context menu (as opposed to just opening the app by double clicking it) and then choose "Open" again at the scare-sheet and this accomplishes the same thing without needing the terminal. Though I'm not 100% sure if I didn't have to change a system preference to allow this or not...

**Comment by tk04** [comment]
Right-clicking and then choosing "Open" may work, but MacOS will still see this app as unverified/untrusted. The goal of running `xattr -c /Applications/Marker.app` is to remove the security attributes attached to the application package so you can open the app without issues.

**Comment by tk04** [comment]
Good to know. When I tested on an M1 Mac, right-clicking and choosing "Open" didn't work. Also, your method doesn't remove the security attributes - so this app is still flagged as unverified/untrusted.
