### ISSUE TITLE
Edit language for codeblock highlighting

### ISSUE THREAD

**Issue by vemonet** [tk04/Marker#9]
Currently Marker does not seems to support editing language for codeblock highlights e.g. 

~~~markdown
```python
import os
```
~~~

Would be nice to have this!

**Comment by tk04** [comment]
The app supports syntax highlighting for code blocks (with language identifiers). Could you clarify more on what you're talking about?

**Comment by vemonet** [comment]
In the editor, I cannot change the language of an existing codeblock, I cannot even see which language is defined for this codeblock

But, indeed creating a new codeblock with a specific language works well


Ideally I would expect that when clicking inside a codeblock there would be a little popup at the bottom right or top right of the codeblock with a text field that shows the language (and autocomplete based on all available languages ideally!). A bit like you have done for Links


Note I am using Ubuntu 22.04 with xorg display (in case that might be a bug)


Really cool implementation btw! Clean code and user-friendly interface, there are not a lot of good markdown editor out there. And this new one might be the best one! Typora is really good but closed source, and Marktext/Muya is ok, but the underlying JS code seems quite messy

**Comment by tk04** [comment]
Thanks for the feedback, added this in [v1.0.1](https://github.com/tk04/Marker/releases/tag/v1.0.1).
